name: "multi event pipeline/workflow"
on:
    push:  #Event: Whenever a push is made to the repostiory on the master branch 
        branches:
            - master
            - test
    pull_request: #Event: Whenever a pull request is made to the master branch
        branches:
            - master
    workflow_dispatch: #Event: Manually trigger the workflow from the GitHub Actions tab

jobs:
    on-push: #Job 1
        if: github.event_name == 'push' #Condition to check if the event is a push event
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on master push"
              run: echo "Running on master push"
    
    on-pull-request: #Job 2
        if: github.event_name == 'pull_request' #Condition to check if the event is a pull request event
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on pull request"
              run: echo "Running on pull request"